// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission8_Team0210.Models;

namespace Mission8_Team0210.Migrations
{
    [DbContext(typeof(ToDoContex))]
    [Migration("20230225025836_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission8_Team0210.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Church"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Mission8_Team0210.Models.ToDoList", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 4,
                            Date = "02/27/2023",
                            IsCompleted = false,
                            Quadrant = 2,
                            Task = "Call mistering sisters!"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            Date = "02/24/2023",
                            IsCompleted = false,
                            Quadrant = 1,
                            Task = "IS 413 Mission 8"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 2,
                            Date = "02/26/2023",
                            IsCompleted = false,
                            Quadrant = 3,
                            Task = "Call home for tuition money!"
                        },
                        new
                        {
                            TaskId = 4,
                            CategoryId = 5,
                            IsCompleted = false,
                            Quadrant = 4,
                            Task = "Read through email from friends on mission"
                        });
                });

            modelBuilder.Entity("Mission8_Team0210.Models.ToDoList", b =>
                {
                    b.HasOne("Mission8_Team0210.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
